/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.timetable.session;

import com.itpm.timetablemanagement.util.Constant;
import com.itpm.timetablemanagement.util.CreateQuery;
import com.itpm.timetablemanagement.util.DBConnection;
import com.timetableitpm.subject.EditSubject;
import com.timetableitpm.subject.Subject;
import com.timetableitpm.subject.ViewSubject;
import java.awt.Dimension;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author HASINI
 */
public class ViewSession extends javax.swing.JFrame {
    ArrayList<Session> sessions = new ArrayList<>();
    TableModel model;
    EditSession editSession = new EditSession();
    int row ;
    int col ;
    /**
     * Creates new form ViewSession
     */
    public ViewSession() {
        initComponents();
        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_session = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 153));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("View Session");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel1)
                .addContainerGap(400, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_session.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Lecturer", "Lecturer 2", "Code", "Subject", "Tag", "GroupID", "NoOf_Student", "Duration", "Update", "Delete"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_session.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sessionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_session);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 334, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 1007, 699);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_sessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sessionMouseClicked
        
        int row = tbl_session.getSelectedRow();
        int col = tbl_session.getSelectedColumn();
        model = tbl_session.getModel();
        
        if(col == 10){
            int x = JOptionPane.showConfirmDialog(ViewSession.this, "Are you sure to Delete", "Delete", JOptionPane.YES_NO_OPTION);
            if(x==0){
                deleteData(row);
            }
        }
        else if(col == 9){
                editSession.setVisible(true);
                editSession.setPreferredSize(new Dimension(200, 400));
                editSession.setLocationRelativeTo(this);
                editSession.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                
                editSession.cmb_lect1.setSelectedItem(model.getValueAt(row, 1));
                editSession.cmb_lect2.setSelectedItem(model.getValueAt(row, 2));
                editSession.txt_code.setText(model.getValueAt(row, 3).toString());
                editSession.cmb_sub.setSelectedItem(model.getValueAt(row, 4));
                editSession.txt_tag.setText(model.getValueAt(row, 5).toString());
                editSession.txt_group.setText(model.getValueAt(row, 6).toString());
                editSession.txt_stno.setText(model.getValueAt(row, 7).toString());
                editSession.txt_duration.setText(model.getValueAt(row, 8).toString());
                  
            
            
        }
    }//GEN-LAST:event_tbl_sessionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSession.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSession().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_session;
    // End of variables declaration//GEN-END:variables

    private void execute() {
         try{
             Connection connection =  DBConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(CreateQuery.getQuery(Constant.GET_SESSION));
             ResultSet resultSet = statement.executeQuery();
             
             while(resultSet.next()){
                DefaultTableModel mod = (DefaultTableModel) tbl_session.getModel();
                Session session = new Session();
                
             
                session.setId(resultSet.getInt("id"));
                session.setLec(resultSet.getString("lect"));
                session.setLec2(resultSet.getString("lect2"));
                session.setCode(resultSet.getString("code"));
                session.setSubject(resultSet.getString("subject"));
                session.setTag(resultSet.getString("tag"));
                session.setgID(resultSet.getString("gID"));
                session.setNoStu(resultSet.getInt("nostudent"));
                session.setDuration(resultSet.getString("duration"));
                
                sessions.add(session);
                
                mod.setRowCount(0);
                
                createTable();
            }
             
         }catch (SQLException | ClassNotFoundException | IOException | 
                ParserConfigurationException | SAXException ex) {
            Logger.getLogger(ViewSubject.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error on data load", "Data error", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    private void deleteData(int row) {
         
        boolean error = false;
        DefaultTableModel model = (DefaultTableModel) tbl_session.getModel();
        
       
         try {
             int id = (int) model.getValueAt(row, 0);
            
             
            Connection connection =  DBConnection.getConnection();
            PreparedStatement statement = connection.prepareStatement(CreateQuery.getQuery(Constant.DELETE_SESSION));
            
            statement.setInt(1, id);
            statement.execute();
            
        } catch (SQLException | ClassNotFoundException | IOException | 
                ParserConfigurationException | SAXException ex) {
            Logger.getLogger(ViewSubject.class.getName()).log(Level.SEVERE, null, ex);
            error = true;
            
             JOptionPane.showMessageDialog(ViewSession.this, "Delete Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
         
         if(!error){
             JOptionPane.showMessageDialog(ViewSession.this, "Delete Succes", "Succes", JOptionPane.DEFAULT_OPTION);
             model.removeRow(row);
             
             
         } 
    }

    private void createTable() {
        
        DefaultTableModel model = (DefaultTableModel) tbl_session.getModel();
        
         Object [] data = new Object[11];
         
         for(int i = 0;i < sessions.size(); i++){
            data[0] = sessions.get(i).getId();
            data[1] = sessions.get(i).getLec();
            data[2] = sessions.get(i).getLec2();
            data[3] = sessions.get(i).getCode();
            data[4] = sessions.get(i).getSubject();
            data[5] = sessions.get(i).getTag();
            data[6] = sessions.get(i).getgID();
            data[7] = sessions.get(i).getNoStu();
            data[8] = sessions.get(i).getDuration();
            data[9] = "Edit";
            data[10] = "Delete";
            
            model.addRow(data);
           
        }
    }
}
