/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itpm.timetablemanagement.form.working_hours;

import com.itpm.timetablemanagement.util.Constant;
import com.itpm.timetablemanagement.util.CreateQuery;
import com.itpm.timetablemanagement.util.DBConnection;
import com.itpm.timetablemanagement.util.DBNEW;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author gayan
 */
public class Week_Edit extends javax.swing.JFrame {

    private int hcount = 0;
    private int mcount = 0;
    private int numOfdays = 0;
    private static int chk_days = 0;
    private static boolean error = false;
    private static ArrayList<String> Arr_days = new ArrayList();
    private static ArrayList<String> days = new ArrayList();
    private Object txt_hour;
    private InsertWorkingHoursWD model = new InsertWorkingHoursWD();
    String loaded_id;
    String loaded_daycount;
    String loaded_hours;
    String loaded_mints;
    String loaded_days;

    /**
     * Creates new form Weekday_Edit
     */
    public Week_Edit() {
        initComponents();

        Arr_days.clear();
        numOfdays = 0;

    }

    Week_Edit(String selectedid, String count, String hrz, String mitz, String days) {
        this();
        this.loaded_id = selectedid;
        this.loaded_daycount = count;
        this.loaded_hours = hrz;
        this.loaded_mints = mitz;
        this.loaded_days = days;
        String dayarray[] = loaded_days.split(",");
        for (int i = 0; i < dayarray.length; i++) {
            String dayarray1 = dayarray[i];
            System.out.println(dayarray1);
            if (dayarray1.equals("Monday")) {
                chk_mon.setSelected(true);
            }
            if (dayarray1.equals("Tuesday")) {
                chk_tue.setSelected(true);
            }
            if (dayarray1.equals("Wednesday")) {
                chk_wed.setSelected(true);
            }
            if (dayarray1.equals("Thursday")) {
                chk_thu.setSelected(true);
            }
            if (dayarray1.equals("Friday")) {
                chk_fri.setSelected(true);
            }
            txt_hour_wd.setText(loaded_hours);
            txt_minutes_wd.setText(loaded_mints);
            if (loaded_daycount.equals("1")) {
                cmb_num_of_days_WD.setSelectedIndex(1);
            }
            if (loaded_daycount.equals("2")) {
                cmb_num_of_days_WD.setSelectedIndex(2);
            }
            if (loaded_daycount.equals("3")) {
                cmb_num_of_days_WD.setSelectedIndex(3);
            }
            if (loaded_daycount.equals("4")) {
                cmb_num_of_days_WD.setSelectedIndex(4);
            }
            if (loaded_daycount.equals("5")) {
                cmb_num_of_days_WD.setSelectedIndex(5);
            }

        }

    }

    Week_Edit(String selectedid, String count, String hrz, String mitz, String days, String stast) {
        this();
        this.loaded_id = selectedid;
        this.loaded_daycount = count;
        this.loaded_hours = hrz;
        this.loaded_mints = mitz;
        this.loaded_days = days;
        String dayarray[] = loaded_days.split(",");
        for (int i = 0; i < dayarray.length; i++) {
            String dayarray1 = dayarray[i];
            System.out.println(dayarray1);
            if (dayarray1.equals("Saturday")) {
                chk_sat.setSelected(true);
            }
            if (dayarray1.equals("Sunday")) {
                chk_sun.setSelected(true);
            }
            int x = Integer.parseInt(loaded_hours);
            int y = Integer.parseInt(loaded_mints);
            spin_hour_WE.setValue(x);
            spin_min_WE.setValue(y);
            if (loaded_daycount.equals("1")) {
                cmb_num_of_days_WE.setSelectedIndex(1);
            }
            if (loaded_daycount.equals("2")) {
                cmb_num_of_days_WE.setSelectedIndex(2);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmb_num_of_days_WD = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        chk_mon = new javax.swing.JCheckBox();
        chk_tue = new javax.swing.JCheckBox();
        chk_wed = new javax.swing.JCheckBox();
        chk_thu = new javax.swing.JCheckBox();
        chk_fri = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmb_num_of_days_WE = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        chk_sat = new javax.swing.JCheckBox();
        chk_sun = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        spin_hour_WE = new javax.swing.JSpinner();
        spin_min_WE = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        update_btn_wd = new javax.swing.JButton();
        txt_days_error = new javax.swing.JLabel();
        txt_hour_wd = new javax.swing.JTextField();
        txt_minutes_wd = new javax.swing.JTextField();
        reset_btn_wd = new javax.swing.JButton();
        update_btn_we = new javax.swing.JButton();
        reset_btn_we = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel3.setBackground(new java.awt.Color(0, 204, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Number of Working Days");

        cmb_num_of_days_WD.setBackground(new java.awt.Color(255, 0, 0));
        cmb_num_of_days_WD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        cmb_num_of_days_WD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_num_of_days_WDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Working Days");

        chk_mon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chk_mon.setText("Monday");
        chk_mon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chk_monMousePressed(evt);
            }
        });

        chk_tue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chk_tue.setText("Tuesday");
        chk_tue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chk_tueMousePressed(evt);
            }
        });

        chk_wed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chk_wed.setText("Wednesday");
        chk_wed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chk_wedMousePressed(evt);
            }
        });

        chk_thu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chk_thu.setText("Thursday");
        chk_thu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chk_thuMousePressed(evt);
            }
        });

        chk_fri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chk_fri.setText("Friday");
        chk_fri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chk_friMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Working Hours");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Number of Working Days");

        cmb_num_of_days_WE.setBackground(new java.awt.Color(255, 0, 0));
        cmb_num_of_days_WE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Working Days");

        chk_sat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chk_sat.setText("Saturday");
        chk_sat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chk_satMousePressed(evt);
            }
        });

        chk_sun.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chk_sun.setText("Sunday");
        chk_sun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chk_sunMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Working Hours");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Hours");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Minutes");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Hours");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Minutes");

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WEEKEND DETAILS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));

        jLabel5.setBackground(new java.awt.Color(0, 0, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("WEEKDAY DETAILS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        update_btn_wd.setBackground(new java.awt.Color(153, 153, 153));
        update_btn_wd.setText("Update New Details");
        update_btn_wd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btn_wdActionPerformed(evt);
            }
        });

        reset_btn_wd.setBackground(new java.awt.Color(153, 153, 153));
        reset_btn_wd.setText("Reset");
        reset_btn_wd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reset_btn_wdMousePressed(evt);
            }
        });

        update_btn_we.setBackground(new java.awt.Color(153, 153, 153));
        update_btn_we.setText("Update");
        update_btn_we.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btn_weActionPerformed(evt);
            }
        });

        reset_btn_we.setBackground(new java.awt.Color(153, 153, 153));
        reset_btn_we.setText("Reset");
        reset_btn_we.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reset_btn_weMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_num_of_days_WD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(chk_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(chk_tue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(txt_minutes_wd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(txt_hour_wd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chk_wed, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(chk_thu, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(chk_fri, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(update_btn_wd, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(reset_btn_wd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(cmb_num_of_days_WE, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(spin_min_WE, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(spin_hour_WE, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(chk_sat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(chk_sun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(239, 239, 239)
                                        .addComponent(txt_days_error, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(update_btn_we, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(reset_btn_we, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(84, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_num_of_days_WD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chk_wed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chk_mon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk_tue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chk_thu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chk_fri, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(update_btn_wd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reset_btn_wd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_hour_wd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_minutes_wd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_days_error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cmb_num_of_days_WE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chk_sat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chk_sun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update_btn_we, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reset_btn_we, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(spin_hour_WE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(spin_min_WE, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 312, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkDays(int value) {
        if (value > numOfdays) {
            txt_days_error.setText("Days cannot exceed number of days : " + numOfdays);
        } else {
            txt_days_error.setText("");
        }
    }

    private boolean checkTime() {

        if (Integer.parseInt(txt_hour_wd.getText()) > 12 || Integer.parseInt(txt_hour_wd.getText()) == 0) {
            return true;
        }

        return false;
    }

    private void cmb_num_of_days_WDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_num_of_days_WDActionPerformed

        numOfdays = cmb_num_of_days_WD.getSelectedIndex();
        checkDays(chk_days);
    }//GEN-LAST:event_cmb_num_of_days_WDActionPerformed

    private void chk_monMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_monMousePressed
        if (chk_mon.isSelected()) {
            chk_days--;
            Arr_days.remove("1");
        } else {
            chk_days++;
            Arr_days.add("1");
        }

        checkDays(chk_days);
    }//GEN-LAST:event_chk_monMousePressed

    private void chk_tueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_tueMousePressed
        if (chk_tue.isSelected()) {
            chk_days--;
            Arr_days.remove("2");
        } else {
            chk_days++;
            Arr_days.add("2");
        }

        checkDays(chk_days);
    }//GEN-LAST:event_chk_tueMousePressed

    private void chk_wedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_wedMousePressed
        if (chk_wed.isSelected()) {
            chk_days--;
            Arr_days.remove("3");
        } else {
            chk_days++;
            Arr_days.add("3");
        }

        checkDays(chk_days);
    }//GEN-LAST:event_chk_wedMousePressed

    private void chk_thuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_thuMousePressed
        if (chk_thu.isSelected()) {
            chk_days--;
            Arr_days.remove("4");
        } else {
            chk_days++;
            Arr_days.add("4");
        }

        checkDays(chk_days);
    }//GEN-LAST:event_chk_thuMousePressed

    private void chk_friMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_friMousePressed
        if (chk_fri.isSelected()) {
            chk_days--;
            Arr_days.remove("5");
        } else {
            chk_days++;
            Arr_days.add("5");
        }

        checkDays(chk_days);
    }//GEN-LAST:event_chk_friMousePressed

    private void chk_satMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_satMousePressed
        if (chk_sat.isSelected()) {
            chk_days--;
            Arr_days.remove("6");
        } else {
            chk_days++;
            Arr_days.add("6");
        }

        checkDays(chk_days);
    }//GEN-LAST:event_chk_satMousePressed

    private void chk_sunMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_sunMousePressed
        if (chk_sun.isSelected()) {
            chk_days--;
            Arr_days.remove("7");
        } else {
            chk_days++;
            Arr_days.add("7");
        }

        checkDays(chk_days);
    }//GEN-LAST:event_chk_sunMousePressed

    private void reset_btn_wdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_btn_wdMousePressed
        cmb_num_of_days_WD.setSelectedIndex(0);
        txt_hour_wd.setText("0");
        txt_minutes_wd.setText("0");
        chk_days = 0;
        numOfdays = 0;
        txt_days_error.setText("");
        Arr_days.clear();
        days.clear();
        txt_hour_wd.setText("");
        txt_minutes_wd.setText("");
    }//GEN-LAST:event_reset_btn_wdMousePressed

    private void reset_btn_weMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_btn_weMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_reset_btn_weMousePressed

    private void update_btn_wdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btn_wdActionPerformed
        try {
            //checking hours and minutes empty
            if (!txt_hour_wd.equals("") || txt_minutes_wd.equals("")) {
                int workinghrs = Integer.parseInt(txt_hour_wd.getText());
                int workminutes = Integer.parseInt(txt_minutes_wd.getText());

                //Checking if the zero values inserted to hours and time
                if (workinghrs == 0 && workminutes == 0) {
                    JOptionPane.showMessageDialog(this, "Invalid Minute or hour Count", "Done", JOptionPane.ERROR_MESSAGE);

                } else {

                    int working_day_count = Integer.parseInt(cmb_num_of_days_WD.getSelectedItem().toString());
                    //sorting days
                    String days = "";
                    if (chk_mon.isSelected()) {
                        days += ",Monday";
                    }
                    if (chk_tue.isSelected()) {
                        days += ",Tuesday";
                    }
                    if (chk_wed.isSelected()) {
                        days += ",Wednesday";
                    }
                    if (chk_thu.isSelected()) {
                        days += ",Thursday";
                    }
                    if (chk_fri.isSelected()) {
                        days += ",Friday";
                    }
                    //insert selected dates into array
                    String no_of_days[] = days.split(",");
                    for (int i = 0; i < no_of_days.length; i++) {
                        String no_of_day = no_of_days[i];
                    }

                    int dayscount = no_of_days.length - 1;
                    if (dayscount == working_day_count) {

                        String status = "Weekdays";
                        DBNEW.closeConn();
                        DBNEW.createCon();
                        DBNEW.iud("update work_day_hour set days_no='" + working_day_count + "',days='" + days + "',hour='" + workinghrs + "',mins='" + workminutes + "' where id='" + loaded_id + "'");
                        DBNEW.closeConn();
                        JOptionPane.showMessageDialog(this, "Data Updated", "Done", JOptionPane.OK_OPTION);
                        this.dispose();
                        new ViewWorkingDayHours().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Selected dates must be equal to Selected count", "Done", JOptionPane.ERROR_MESSAGE);

                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_update_btn_wdActionPerformed

    private void update_btn_weActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btn_weActionPerformed
      try {
            //checking hours and minutes empty
            
                int workinghrs = Integer.parseInt(spin_hour_WE.getValue().toString());
                int workminutes = Integer.parseInt(spin_min_WE.getValue().toString());

                //Checking if the zero values inserted to hours and time
                if (workinghrs == 0 && workminutes == 0) {
                    JOptionPane.showMessageDialog(this, "Invalid Minute or hour Count", "Done", JOptionPane.ERROR_MESSAGE);

                } else {

                    int working_day_count = Integer.parseInt(cmb_num_of_days_WE.getSelectedItem().toString());
                    //sorting days
                    String days = "";
                    if (chk_sat.isSelected()) {
                        days += ",Saturday";
                    }
                    if (chk_sun.isSelected()) {
                        days += ",Sunday";
                    }
                    //insert selected dates into array
                    String no_of_days[] = days.split(",");
                    for (int i = 0; i < no_of_days.length; i++) {
                        String no_of_day = no_of_days[i];
                    }

                    int dayscount = no_of_days.length - 1;
                    if (dayscount == working_day_count) {

                       
                        DBNEW.closeConn();
                        DBNEW.createCon();
                        DBNEW.iud("update work_day_hour set days_no='" + working_day_count + "',days='" + days + "',hour='" + workinghrs + "',mins='" + workminutes + "' where id='" + loaded_id + "'");
                        DBNEW.closeConn();
                        JOptionPane.showMessageDialog(this, "Data Updated", "Done", JOptionPane.OK_OPTION);
                        this.dispose();
                        new ViewWorkingDayHours().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Selected dates must be equal to Selected count", "Done", JOptionPane.ERROR_MESSAGE);

                    }
                }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_update_btn_weActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewWorkingDayHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewWorkingDayHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewWorkingDayHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewWorkingDayHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewWorkingDayHours().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk_fri;
    private javax.swing.JCheckBox chk_mon;
    private javax.swing.JCheckBox chk_sat;
    private javax.swing.JCheckBox chk_sun;
    private javax.swing.JCheckBox chk_thu;
    private javax.swing.JCheckBox chk_tue;
    private javax.swing.JCheckBox chk_wed;
    private javax.swing.JComboBox<String> cmb_num_of_days_WD;
    private javax.swing.JComboBox<String> cmb_num_of_days_WE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton reset_btn_wd;
    private javax.swing.JButton reset_btn_we;
    private javax.swing.JSpinner spin_hour_WE;
    private javax.swing.JSpinner spin_min_WE;
    private javax.swing.JLabel txt_days_error;
    private javax.swing.JTextField txt_hour_wd;
    private javax.swing.JTextField txt_minutes_wd;
    private javax.swing.JButton update_btn_wd;
    private javax.swing.JButton update_btn_we;
    // End of variables declaration//GEN-END:variables
}
