/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itpm.student;

import com.itpm.timetablemanagement.util.Constant;
import com.itpm.timetablemanagement.util.CreateQuery;
import com.itpm.timetablemanagement.util.DBConnection;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Anjelo
 */
public class idGenerate extends javax.swing.JFrame {
    
     private Connection connection;
     PreparedStatement pstYns, pstDp, pstGno, pst, pst2;
     ResultSet rs;

    /**
     * Creates new form idGenerate
     */
    public idGenerate() {
        initComponents();
        showGroupIDList();
        txt_id.setVisible(false);
        AcademicYSelection();
        degreePSeletion();
        groupNoSeletion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JpanelGroup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        select_ys = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        select_dp = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        select_gno = new javax.swing.JComboBox();
        ys_id = new javax.swing.JTextField();
        dp_id = new javax.swing.JTextField();
        gno_id = new javax.swing.JTextField();
        txt_groupID = new javax.swing.JTextField();
        txt_error = new javax.swing.JTextField();
        btn_groupID = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_groupID = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 255, 204));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        JpanelGroup.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Academic Year & Semester");

        select_ys.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--select--" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Degree Programme");

        select_dp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--select--" }));
        select_dp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_dpActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Group Number");

        select_gno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--select--" }));

        ys_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ys_idActionPerformed(evt);
            }
        });

        gno_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gno_idActionPerformed(evt);
            }
        });

        btn_groupID.setText("Generate ID");
        btn_groupID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_groupIDMousePressed(evt);
            }
        });

        btn_save.setText("SAVE");
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_saveMousePressed(evt);
            }
        });

        javax.swing.GroupLayout JpanelGroupLayout = new javax.swing.GroupLayout(JpanelGroup);
        JpanelGroup.setLayout(JpanelGroupLayout);
        JpanelGroupLayout.setHorizontalGroup(
            JpanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelGroupLayout.createSequentialGroup()
                .addGroup(JpanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelGroupLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JpanelGroupLayout.createSequentialGroup()
                        .addGroup(JpanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelGroupLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_groupID)
                                .addGap(77, 77, 77))
                            .addGroup(JpanelGroupLayout.createSequentialGroup()
                                .addGroup(JpanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addGroup(JpanelGroupLayout.createSequentialGroup()
                                        .addGap(165, 165, 165)
                                        .addComponent(txt_error, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(160, 160, 160)
                                        .addComponent(btn_save)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(JpanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(select_dp, 0, 480, Short.MAX_VALUE)
                            .addComponent(select_gno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(select_ys, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_groupID, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))))
                .addGap(10, 10, 10)
                .addGroup(JpanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ys_id, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(dp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(gno_id, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
        );
        JpanelGroupLayout.setVerticalGroup(
            JpanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelGroupLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(JpanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JpanelGroupLayout.createSequentialGroup()
                        .addGroup(JpanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(select_ys, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ys_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2))
                    .addGroup(JpanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(select_dp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(JpanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelGroupLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_error, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpanelGroupLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(JpanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(select_gno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gno_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JpanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_groupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_groupID))
                        .addGap(18, 18, 18)
                        .addComponent(btn_save)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );

        tbl_groupID.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Generate ID", "Edit", "Delete"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_groupID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_groupIDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_groupID);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpanelGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(JpanelGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1009, 707));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ys_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ys_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ys_idActionPerformed

    private void select_dpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_dpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_dpActionPerformed

    private void gno_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gno_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gno_idActionPerformed

    private void btn_groupIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_groupIDMousePressed
        
        String ys = select_ys.getSelectedItem().toString();
        String dp = select_dp.getSelectedItem().toString();
        String gno = select_gno.getSelectedItem().toString();
        
        
        if(select_ys.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(idGenerate.this, "Lecturer id cannot empty! ", "Data missing", JOptionPane.ERROR_MESSAGE);
        }
        else if(select_dp.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(idGenerate.this, "Lecture id Should be 6 characters", "Data missing", JOptionPane.ERROR_MESSAGE);
        }
        else{
            txt_groupID.setText(ys + "." + dp + "." + gno);
            
        }
    }//GEN-LAST:event_btn_groupIDMousePressed

    private void btn_saveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMousePressed
        
        boolean error = false;
        try{
            DefaultTableModel model = (DefaultTableModel)tbl_groupID.getModel();
            connection = DBConnection.getConnection();
            
            
            if(txt_groupID.getText().contentEquals("")){
                 JOptionPane.showMessageDialog(idGenerate.this, "Group ID cannot be empty!", "Data missing", JOptionPane.ERROR_MESSAGE);
                 txt_error.setText("Generate ID");
                  error = true;
            }
            else{
                txt_error.setText("");
                
                PreparedStatement statement = connection.prepareStatement(CreateQuery.getQuery(Constant.INSERT_GROUP_ID));
                statement.setString(1, txt_groupID.getText().toUpperCase());
                statement.executeUpdate();
                model.setRowCount(0);
                
                showGroupIDList();
                txt_groupID.setText("");
                JOptionPane.showMessageDialog(null, "Successfull Added Group ID");
                
            }
            
            
        }catch(SQLException | ClassNotFoundException | IOException | ParserConfigurationException | SAXException ex){
            Logger.getLogger(GenerateID.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_btn_saveMousePressed

    private void tbl_groupIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_groupIDMouseClicked
       int i = tbl_groupID.getSelectedRow();
       TableModel model = tbl_groupID.getModel();
       txt_id.setText(model.getValueAt(i, 0).toString());
       txt_groupID.setText(model.getValueAt(i, 1).toString());
       
       int row = tbl_groupID.getSelectedRow();
        int col = tbl_groupID.getSelectedColumn();
        model = tbl_groupID.getModel();

        if(col == 3){
            int x = JOptionPane.showConfirmDialog(idGenerate.this, "Are you sure to Delete", "Delete", JOptionPane.YES_NO_OPTION);
            if(x==0){
                deleteData(row);
            }

        }
         if(col == 2){
             updateData(row);
        }
       
    }//GEN-LAST:event_tbl_groupIDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(idGenerate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(idGenerate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(idGenerate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(idGenerate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new idGenerate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelGroup;
    private javax.swing.JButton btn_groupID;
    private javax.swing.JButton btn_save;
    private javax.swing.JTextField dp_id;
    private javax.swing.JTextField gno_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox select_dp;
    private javax.swing.JComboBox select_gno;
    private javax.swing.JComboBox select_ys;
    private javax.swing.JTable tbl_groupID;
    private javax.swing.JTextField txt_error;
    private javax.swing.JTextField txt_groupID;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField ys_id;
    // End of variables declaration//GEN-END:variables

    private void AcademicYSelection() {
       
         try{  
        connection = DBConnection.getConnection();
        String query = "select * from academic";
        pst = connection.prepareStatement(query);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
            String yNs = rs.getString("ys");
            select_ys.addItem(yNs);
        }
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void degreePSeletion() {
        
         try{  
        connection = DBConnection.getConnection();
        String query = "select * from degree_program";
        pst = connection.prepareStatement(query);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
            String dp = rs.getString("dp");
            select_dp.addItem(dp);
        }
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        } 
    }

    private void groupNoSeletion() {
        
        try{  
        connection = DBConnection.getConnection();
        String query = "select * from groupNo";
        pst = connection.prepareStatement(query);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
            String gNo = rs.getString("gNo");
            select_gno.addItem(gNo);
        }
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        } 
    }

    private void showGroupIDList() {
         ArrayList<GenerateID> list = getGroupIDList();
        DefaultTableModel model = (DefaultTableModel)tbl_groupID.getModel();
        Object[] row = new Object[4];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getgId();
            row[2] = "Edit";
            row[3] = "Delete";
            
            model.addRow(row);
        }
        
    }

    private void deleteData(int row) {
         boolean error = false;
        DefaultTableModel mod = (DefaultTableModel) tbl_groupID.getModel();
        
         try {
             int id = (int) mod.getValueAt(row, 0);
            
             
            Connection connection =  DBConnection.getConnection();
            PreparedStatement statement = connection.prepareStatement(CreateQuery.getQuery(Constant.DELETE_GROUP_ID));
            
            statement.setInt(1, id);
            statement.execute();
            
        } catch (SQLException | ClassNotFoundException | IOException | 
                ParserConfigurationException | SAXException ex) {
            Logger.getLogger(idGenerate.class.getName()).log(Level.SEVERE, null, ex);
            error = true;
            
             JOptionPane.showMessageDialog(idGenerate.this, "Delete Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
         
         if(!error){
             JOptionPane.showMessageDialog(idGenerate.this, "Delete Succes", "Succes", JOptionPane.DEFAULT_OPTION);
             mod.removeRow(row);
             
             
         }
        
        
    }

    private void updateData(int row) {
        
    }

    private ArrayList<GenerateID> getGroupIDList() {
        ArrayList<GenerateID> list = new ArrayList<GenerateID>();
        try{
        connection = DBConnection.getConnection();
        String querry = "select * from group_id";
        Statement st;
        ResultSet rs;
        
        st = connection.createStatement();
        rs= st.executeQuery(querry);
        GenerateID GenrateID;
        while(rs.next())
        {
            GenrateID = new GenerateID(rs.getInt("id"), rs.getString("gId"));
            list.add(GenrateID);
        }
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        return list;
    }
       
    }

